"""empty message

Revision ID: d20ff2f578c6
Revises: a1e7b8d6dc51
Create Date: 2024-04-19 22:34:53.199973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20ff2f578c6'
down_revision: Union[str, None] = 'a1e7b8d6dc51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_template', 'additional_fields',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_template', 'additional_fields',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
